name: 'hostwithquantum/setup-quantum-cli'
description: 'Setup the quantum-cli on GitHub Actions'
branding:
  icon: 'zap'
  color: 'red'
inputs:
  username:
    required: true
    description: username
  password:
    required: true
    description: password
  version:
    required: true
    description: version
    default: '2.8.4'
runs:
  using: "composite"
  steps:
  - name: install quantum-cli
    run: |
      curl \
        -H 'Cache-Control: no-cache' \
        "https://cli.planetary-quantum.com/quantum-cli-linux-amd64?v=${{ inputs.version }}" \
        -o ${{ github.action_path }}/quantum-cli \
        && chmod +x ${{ github.action_path }}/quantum-cli
    shell: bash
  - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
    shell: bash
  - run: quantum-cli -v
    shell: bash
  - run: echo "QUANTUM_USER=${{ inputs.username }}" >> "$GITHUB_ENV"
    shell: bash
  - run: echo "QUANTUM_PASSWORD=${{ inputs.password }}" >> "$GITHUB_ENV"
    shell: bash
