name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: {}

jobs:
  test:
    permissions:
      security-events: write
      contents: read
      actions: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: zizmorcore/zizmor-action@71321a20a9ded102f6e9ce5718a2fcec2c4f70d8 # v0.5.2


  e2e:
    needs: test
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux (amd64)
          - os: ubuntu-24.04-arm
            name: Linux (arm64)
          - os: macos-15-intel
            name: macOS 15 (amd64)
          - os: macos-26-intel
            name: macOS 26 (amd64)
          - os: macos-latest
            name: macOS (arm64)
          - os: windows-latest
            name: Windows (amd64)

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: ./
        with:
          api-key: "placeholder"

      - name: Show version
        run: quantum-cli -v
        shell: bash

      - name: Show help
        run: quantum-cli -h
        shell: bash
