name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: Linux (amd64)
          - os: ubuntu-24.04-arm
            name: Linux (arm64)
          - os: macos-15-intel
            name: macOS 15 (amd64)
          - os: macos-26-intel
            name: macOS 26 (amd64)
          - os: macos-latest
            name: macOS (arm64)
          - os: windows-latest
            name: Windows (amd64)

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v6

      - uses: ./
        with:
          api-key: "placeholder"

      - name: Show version
        run: quantum-cli -v
        shell: bash

      - name: Show help
        run: quantum-cli -h
        shell: bash
